/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kuis2;

/**
 *
 * @author Zeta Arsetya
 */
public class Kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis2
     */
    public Kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dskn = new javax.swing.JTextField();
        Bilangan1 = new javax.swing.JTextField();
        Bilangan2 = new javax.swing.JTextField();
        Bilangan3 = new javax.swing.JTextField();
        Bilangan4 = new javax.swing.JTextField();
        Keluar = new javax.swing.JButton();
        Proses = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(Dskn);
        Dskn.setBounds(230, 200, 80, 30);
        getContentPane().add(Bilangan1);
        Bilangan1.setBounds(230, 40, 80, 30);
        getContentPane().add(Bilangan2);
        Bilangan2.setBounds(230, 80, 80, 30);
        getContentPane().add(Bilangan3);
        Bilangan3.setBounds(230, 120, 80, 30);
        getContentPane().add(Bilangan4);
        Bilangan4.setBounds(230, 160, 80, 30);

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar);
        Keluar.setBounds(270, 260, 90, 30);

        Proses.setText("Proses");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });
        getContentPane().add(Proses);
        Proses.setBounds(30, 260, 90, 30);

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus);
        Hapus.setBounds(150, 260, 90, 30);

        Hasil.setColumns(20);
        Hasil.setRows(5);
        jScrollPane1.setViewportView(Hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(76, 310, 210, 140);

        jLabel1.setFont(new java.awt.Font("Amatic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 10, 160, 20);

        jLabel2.setText("Diskon");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 200, 100, 30);

        jLabel4.setText("Harga barang 1");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 40, 100, 30);

        jLabel5.setText("Harga barang 2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 80, 100, 30);

        jLabel6.setText("Harga barang 3");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 120, 100, 30);

        jLabel7.setText("Harga barang 4");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 160, 100, 30);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        // TODO add your handling code here:
        int bil1 = Integer.parseInt(Bilangan1.getText());
        int bil2 = Integer.parseInt(Bilangan2.getText());
        int bil3 = Integer.parseInt(Bilangan3.getText());
        int bil4 = Integer.parseInt(Bilangan4.getText());
        int diskon = Integer.parseInt(Dskn.getText());
        String keterangan = "";
        
        if (diskon == 50){
            int total = (bil1+bil2+bil3+bil4);
            int hasil = total * diskon / 100;
            keterangan = "Diskon= "+diskon+"\n"+"Total harga= "+total+
                    "\n"+"Total Bayar ="+hasil;
        }
        else if (diskon == 100){
            int total = (bil1+bil2+bil3+bil4);
            int hasil = total * 0;
            keterangan = "Diskon= "+diskon+"\n"+"Total harga= "+total+
                    "\n"+"Total Bayar ="+hasil;
        }
        else if (diskon == 75){
            int total = (bil1+bil2+bil3+bil4);
            int hasil = total * diskon / 100;
            keterangan = "Diskon= "+diskon+"\n"+"Total harga= "+total+
                    "\n"+"Total Bayar ="+hasil;
        }
        else if (diskon == 0){
            int total = (bil1+bil2+bil3+bil4);
            int hasil = total;
            keterangan = "Diskon= "+diskon+"\n"+"Total harga= "+total+
                    "\n"+"Total Bayar ="+hasil;
        }
        else {
            keterangan = " ";
        }
        Hasil.setText("Harga Barang 1 :"+bil1+"\n"+"Harga Barang 2 :"+bil2+"\n"+"Harga Barang 3 :"+bil3+
                "\n"+"Harga Barang 4 :"+bil4+"\n"+keterangan);
    }//GEN-LAST:event_ProsesActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        Hasil.setText("");
        Bilangan1.setText("");
        Bilangan2.setText("");
        Bilangan3.setText("");
        Bilangan4.setText("");
        Dskn.setText("");
    }//GEN-LAST:event_HapusActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
    dispose()    ;
// TODO add your handling code here:
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bilangan1;
    private javax.swing.JTextField Bilangan2;
    private javax.swing.JTextField Bilangan3;
    private javax.swing.JTextField Bilangan4;
    private javax.swing.JTextField Dskn;
    private javax.swing.JButton Hapus;
    private javax.swing.JTextArea Hasil;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Proses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
