/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan5;

/**
 *
 * @author Zeta Arsetya
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2(String nm, String abs,String kls, String jur, String alm) {
        initComponents();
        idhasil1.setText(nm);
        idhasil2.setText(abs);
        idhasil3.setText(kls);
        idhasil4.setText(jur);
        idhasil5.setText(alm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idhasil5 = new javax.swing.JLabel();
        idhasil1 = new javax.swing.JLabel();
        idhasil2 = new javax.swing.JLabel();
        idhasil3 = new javax.swing.JLabel();
        idhasil4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        idhasil5.setText("Hasil 5");
        getContentPane().add(idhasil5);
        idhasil5.setBounds(50, 130, 34, 14);

        idhasil1.setText("Hasil 1");
        getContentPane().add(idhasil1);
        idhasil1.setBounds(50, 50, 31, 14);

        idhasil2.setText("Hasil 2");
        getContentPane().add(idhasil2);
        idhasil2.setBounds(50, 70, 34, 14);

        idhasil3.setText("Hasil 3");
        getContentPane().add(idhasil3);
        idhasil3.setBounds(50, 90, 34, 14);

        idhasil4.setText("Hasil 4");
        getContentPane().add(idhasil4);
        idhasil4.setBounds(50, 110, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idhasil1;
    private javax.swing.JLabel idhasil2;
    private javax.swing.JLabel idhasil3;
    private javax.swing.JLabel idhasil4;
    private javax.swing.JLabel idhasil5;
    // End of variables declaration//GEN-END:variables
}
