/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan5;

/**
 *
 * @author Zeta Arsetya
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Alamat = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        idComboBox1 = new javax.swing.JComboBox<>();
        tkj = new javax.swing.JRadioButton();
        rpl = new javax.swing.JRadioButton();
        Absen = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        send = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Alamat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(Alamat);
        Alamat.setBounds(160, 210, 140, 20);

        Nama.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(Nama);
        Nama.setBounds(160, 90, 140, 20);

        idComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        idComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XI RPL 1", "XI RPL 2", "XI RPL 3", "XI RPL 4", "XI RPL 5", "XI RPL 6" }));
        getContentPane().add(idComboBox1);
        idComboBox1.setBounds(160, 150, 140, 20);

        tkj.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tkj.setText("TKJ");
        getContentPane().add(tkj);
        tkj.setBounds(250, 180, 50, 23);

        rpl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rpl.setText("RPL");
        getContentPane().add(rpl);
        rpl.setBounds(160, 180, 50, 23);

        Absen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(Absen);
        Absen.setBounds(160, 120, 140, 20);

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setText("EXIT");
        getContentPane().add(exit);
        exit.setBounds(200, 250, 73, 23);

        send.setBackground(new java.awt.Color(255, 255, 255));
        send.setText("SEND");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        getContentPane().add(send);
        send.setBounds(80, 250, 59, 23);

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 204));
        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 90, 60, 14);

        jLabel2.setFont(new java.awt.Font("Amatic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 204));
        jLabel2.setText("BIODATA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 20, 120, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 204));
        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 120, 60, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 204));
        jLabel4.setText("Kelas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 150, 60, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 204));
        jLabel5.setText("Jurusan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 180, 60, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 204));
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 210, 60, 14);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zeta Arsetya\\Pictures\\aa.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 10, 240, 280);

        setBounds(0, 0, 488, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
        String nama = Nama.getText();
        String absen = Absen.getText();
        String kelas = idComboBox1.getSelectedItem().toString();
        String jurusan = "";
        String alamat = Alamat.getText();
        
        if (rpl.isSelected())
            jurusan = "RPL";
        else if (tkj.isSelected())
            jurusan = "TKJ";
        else
            
            if (idComboBox1.getSelectedItem() == "XI RPL 1"){
            }
            if (idComboBox1.getSelectedItem() == "XI RPL 2"){
            }
            if (idComboBox1.getSelectedItem() == "XI RPL 3"){
            }
            if (idComboBox1.getSelectedItem() == "XI RPL 4"){
            }
            if (idComboBox1.getSelectedItem() == "XI RPL 5"){
            }
            if (idComboBox1.getSelectedItem() == "XI RPL 6"){
            }
        new Frame2 (nama, absen, kelas, jurusan, alamat).setVisible(true);
    }//GEN-LAST:event_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Nama;
    private javax.swing.JButton exit;
    private javax.swing.JComboBox<String> idComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rpl;
    private javax.swing.JButton send;
    private javax.swing.JRadioButton tkj;
    // End of variables declaration//GEN-END:variables
}
